<a href="https://colab.research.google.com/github/MURALAAYYAPPA/Deep-Learning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Write a program to find the order and type of a tensor
import tensorflow as tf
a=tf.constant(98)
b=tf.constant([4,5,6])
c=tf.constant([[1,2,3],[4,5,6]])
d=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('Tensor-A=',a)
print('Tensor-B=',b)
print('Tensor-C=',c)
print('Tensor-D=',d)
print('Rank of tensor-a is',tf.rank(a),'and it is a scalar.')
print('Rank of tensor-b is',tf.rank(b),'and it is a vector.')
print('Rank of tensor-c is',tf.rank(c),'and it is a matrix.')
print('Rank of tensor-d is',tf.rank(d),'and it is a 3-D tensor.')


Tensor-A= tf.Tensor(98, shape=(), dtype=int32)
Tensor-B= tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Tensor-C= tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor-D= tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Rank of tensor-a is tf.Tensor(0, shape=(), dtype=int32) and it is a scalar.
Rank of tensor-b is tf.Tensor(1, shape=(), dtype=int32) and it is a vector.
Rank of tensor-c is tf.Tensor(2, shape=(), dtype=int32) and it is a matrix.
Rank of tensor-d is tf.Tensor(3, shape=(), dtype=int32) and it is a 3-D tensor.


In [ ]:
#write a program on second order tensors performing various operations
#Arthimetic,comparative-element wise operations
a=tf.constant([[1,3,5],[2,4,6]])
b=tf.constant([[7,8,9],[3,4,5]])
print('Elements in Tensor-A=',a)
print('Elements in Tensor-B=',b)
print('Element wise sum of two tensors=',tf.add(a,b))
print('Element wise difference of two tensors=',tf.subtract(b,a))
print('Element wise product of two tensors=',tf.multiply(a,b))
print('Element wise division of two tensors=',tf.divide(a,b))
print('Element wise power of two tensors=',tf.pow(a,b))
print('Element wise remainder of two tensors=',tf.math.mod(a,b))
#Comparative operators
print('Check for the element wise equality of tensors:',tf.equal(a,b))
print('Check for the element wise inequality of tensors:',tf.not_equal(a,b))
print('Check for the element wise greater value of tensors:',tf.greater(a,b))
print('Check for the element wise less value of tensors:',tf.less(a,b))

Elements in Tensor-A= tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Elements in Tensor-B= tf.Tensor(
[[7 8 9]
 [3 4 5]], shape=(2, 3), dtype=int32)
Element wise sum of two tensors= tf.Tensor(
[[ 8 11 14]
 [ 5  8 11]], shape=(2, 3), dtype=int32)
Element wise difference of two tensors= tf.Tensor(
[[ 6  5  4]
 [ 1  0 -1]], shape=(2, 3), dtype=int32)
Element wise product of two tensors= tf.Tensor(
[[ 7 24 45]
 [ 6 16 30]], shape=(2, 3), dtype=int32)
Element wise division of two tensors= tf.Tensor(
[[0.14285714 0.375      0.55555556]
 [0.66666667 1.         1.2       ]], shape=(2, 3), dtype=float64)
Element wise power of two tensors= tf.Tensor(
[[      1    6561 1953125]
 [      8     256    7776]], shape=(2, 3), dtype=int32)
Element wise remainder of two tensors= tf.Tensor(
[[1 3 5]
 [2 0 1]], shape=(2, 3), dtype=int32)
Check for the element wise equality of tensors: tf.Tensor(
[[False False False]
 [False  True False]], shape=(2, 3), dtype=bool)
Check for the element wise ineq

In [ ]:
#write a program to find the value of activation functions.
#Sigmoid,Tanh,ReLU
import tensorflow as tf
import numpy as np
x=np.array([0,1.5,2,1])
print('Sigmoid function value=',tf.sigmoid(x))
print('Tanh function value=',tf.tanh(x))
print('ReLU function value=',tf.nn.relu(x))

Sigmoid function value= tf.Tensor([0.5        0.81757448 0.88079708 0.73105858], shape=(4,), dtype=float64)
Tanh function value= tf.Tensor([0.         0.90514825 0.96402758 0.76159416], shape=(4,), dtype=float64)
ReLU function value= tf.Tensor([0.  1.5 2.  1. ], shape=(4,), dtype=float64)


In [ ]:
#write a program to implement logic gate using MP neuron
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
w=np.array([1,1])
yact=np.array([0,1,1,0])
print('Input matrix:',x)
print('Weight matrix:',w)
print('Actual output:',yact)
y=np.dot(x,w.T)
print('Total input:',y)
for i in range(len(y)):
    if y[i]>=1:
        y[i]=1
    else:
      y[i]=0
print('Predicted output:',y)
print('Check for the correctness of predicted output:\n',np.allclose(y,yact))

Input matrix: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Weight matrix: [1 1]
Actual output: [0 1 1 0]
Total input: [0 1 1 2]
Predicted output: [0 1 1 1]
Check for the correctness of predicted output:
 False
